name: Best Practices Assignment - Automatically Deploy to Staging

on:
  workflow_run:
    workflows: ["Best Practices Assignment - Commit Phase"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d7gp7n7aqgkc739h9gl0
          api-key: ${{ secrets.RENDER_TOKEN }}
